### ISSUE TITLE
Can not create backup with cinder backend

### ISSUE THREAD

**Issue by datle1** [Lirt/velero-plugin-for-openstack#29]
Hi,
I 'm trying to use velero-plugin-for-openstack for velero. I installed k8s in VM of Openstack Rocky. My openstack uses ceph-backend. I deployed velero include plugin from CLI:
```
velero install --provider "community.openstack.org/openstack" --plugins lirt/velero-plugin-for-openstack:v0.3.0 --bucket velero-bucket  --no-secret
```
After authentication is successful, there is error when create backup store. Seem, default plugin use swift but I only want to use cinder driver. How to get that ?
```
time="2021-10-25T06:58:30Z" level=info msg="Trying to authenticate against Openstack using environment variables (including application credentials) or using files ~/.config/openstack/clouds.yaml, /etc/openstack/clouds.yaml and ./clouds.yaml" cmd=/plugins/velero-plugin-swift controller=backup-sync logSource="/go/src/github.com/Lirt/velero-plugin-swift/src/utils/auth.go:50" pluginName=velero-plugin-swift
time="2021-10-25T06:58:31Z" level=info msg="Authentication successful" cmd=/plugins/velero-plugin-swift controller=backup-sync logSource="/go/src/github.com/Lirt/velero-plugin-swift/src/utils/auth.go:70" pluginName=velero-plugin-swift
time="2021-10-25T06:58:31Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = failed to create swift storage object: No suitable endpoint could be found in the service catalog." logSource="pkg/controller/backup_sync_controller.go:175"
```
Hope your reply soon, @Lirt

**Comment by Lirt** [comment]
Hello @datle1 

sorry for late answer. 

Velero at current state must have object storage plugin to create volume snapshots. It is done like that because it needs to store metadata about the backup and then know how to restore the backup from the metadata. It is not documented very well, but you can find multiple issues in their GitHub that says the same.

Here are 2 examples where this is noted.

> Velero needs an object storage where to save all resource backups and the information about snapshot backups.
https://tanzucommunityedition.io/docs/latest/package-readme-velero-1.6.3/

> Velero needs two things to take a backup with snapshots - an object store plugin for storing the Velero backup metadata and a volume snapshotter plugin to take the actual snapshots.
- https://github.com/vmware-tanzu/velero/issues/4287#issuecomment-956922858

Maybe for your use case it would be better to use tool like https://github.com/stashed/stash?

Or as a workaround you can install MinIO which provides object storage where backups can be stored.
